CFSSL_MULTIROOTCA_CMD_ARGS: -l primary -loglevel 1

CFSSL_MUTLTIROOTCA_HTTPS: false
CFSSL_MUTLTIROOTCA_HTTPS_CRT_FILENAME: cfssl-mutlirootca.crt
CFSSL_MUTLTIROOTCA_HTTPS_KEY_FILENAME: cfssl-mutlirootca.key
