#!/bin/bash -e

CFSSL_MULTIROOTCA_DEFAULT_LABEL_PARAM=""
CFSSL_MULTIROOTCA_LOGLEVEL_PARAM=""
CFSSL_MULTIROOTCA_HTTPS_PARAM=""

[[ -n "$CFSSL_MULTIROOTCA_DEFAULT_LABEL" ]] && CFSSL_MULTIROOTCA_DEFAULT_LABEL_PARAM="-l $CFSSL_MULTIROOTCA_DEFAULT_LABEL"
[[ -n "$CFSSL_MULTIROOTCA_LOGLEVEL" ]] && CFSSL_MULTIROOTCA_LOGLEVEL_PARAM="-loglevel $CFSSL_MULTIROOTCA_LOGLEVEL"

if [ "${CFSSL_MUTLTIROOTCA_HTTPS,,}" == "true" ]; then
  CFSSL_MULTIROOTCA_HTTPS_PARAM="-tls-cert /container/service/multirootca/assets/certs/$CFSSL_MUTLTIROOTCA_HTTPS_CRT_FILENAME -tls-key /container/service/multirootca/assets/certs/$CFSSL_MUTLTIROOTCA_HTTPS_KEY_FILENAME"
fi

echo "exec multirootca -a 0.0.0.0:8888 -roots /container/service/multirootca/assets/roots.conf $CFSSL_MULTIROOTCA_DEFAULT_LABEL_PARAM $CFSSL_MULTIROOTCA_LOGLEVEL_PARAM $CFSSL_MULTIROOTCA_HTTPS_PARAM"
exec multirootca -a 0.0.0.0:8888 -roots /container/service/multirootca/assets/roots.conf $CFSSL_MULTIROOTCA_DEFAULT_LABEL_PARAM $CFSSL_MULTIROOTCA_LOGLEVEL_PARAM $CFSSL_MULTIROOTCA_HTTPS_PARAM
